### ISSUE TITLE
Issue with modified or inserted/deleted row

### ISSUE THREAD

**Issue by lmonno** [edwindj/daff#20]
Hi, thank you for the very useful package.
In the same comparison, I find sometimes modified rows and sometimes a couple of inserted/deleted rows.
It is very strange because the format of keys columns is the same and I don't find difference in the key columns. 
Tks

**Comment by gwarnes-mdsol** [comment]
This is a problem with the underlying daff library (http://paulfitz.github.io/daff/) and has been reported to the developer as Issue #91 (https://github.com/paulfitz/daff/issues/91).

**Comment by lmonno** [comment]
thanks
