### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by rajesh06** [edwindj/daff#34]
Will `daff` be available on CRAN again at some point?

**Comment by jmaspons** [comment]
It seems that all issues are fixed in the main branch https://cran-archive.r-project.org/web/checks/2022/2022-11-20_check_results_daff.html

It just needs to resend the package to CRAN.

**Comment by krlmlr** [comment]
@edwindj: Do you need help?

We have a few NOTEs, and differences in golden tests: https://win-builder.r-project.org/jaDCDy5XYY35/00check.log .

Results from winbuilder: https://win-builder.r-project.org/jaDCDy5XYY35/ .

**Comment by edwindj** [comment]
@krlmlr Thanks for your offer! 
Mostly a lack of time: will look into it this weekend

**Comment by brownag** [comment]
Hello! Just wanted to see if there was any progress on the re-submission front. Thank you for this excellent package!

**Comment by edwindj** [comment]
Back on CRAN, sorry for the delay and thanks for your concerns!
