### ISSUE TITLE
Handle NAs

### ISSUE THREAD

**Issue by eusebe** [edwindj/daff#5]
Hi, 

Thank you for this very usefull package!

I tried the following code:

```{r}
> y <- iris[1:3,]
> x <- y
> x$Sepal.Width[2] <- NA
> y
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
> x
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9          NA          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
> patch <- diff_data(y, x)
> render_diff(patch)
```
<table>
<tr><th>@@</th><th>Sepal.Length</th><th>Sepal.Width</th><th>Petal.Length</th><th>Petal.Width</th><th>Species</th></tr>
<tr><td></td><td>5.1</td><td>3.5</td><td>1.4</td><td>0.2</td><td>setosa</td></tr>
<tr class="modify"><td class="modify">-></td><td>4.9</td><td class="modify">3->1.4</td><td class="modify">1.4->0.2</td><td class="modify">0.2->setosa</td><td class="modify">setosa->NULL</td></tr>
<tr><td></td><td>4.7</td><td>3.2</td><td>1.3</td><td>0.2</td><td>setosa</td></tr>
</table>

Is it expected?

Best, 
David

**Comment by edwindj** [comment]
Thanks! You just uncovered a bug :-).

**Comment by edwindj** [comment]
Working on it: 
It has to do with the jsonlite communication:

```S
jsonlite::toJSON(data.frame(a=1,b=NA))
```
results in
```
[{a: 1}]
```

**Comment by jeroenooms** [comment]
Perhaps you can use 'na=null' or na=string in tojson

**Comment by edwindj** [comment]
@jeroenooms Thanks! I solved it differently: since `daff.js` uses a matrix internally I used 
`jsonlite::toJSON(..., dataframe='values')`.

**Comment by eusebe** [comment]
Quick and clean, thanks!
David
