### ISSUE TITLE
Error: "Ordering took too long, something went wrong" when calling diff_data with large dataset inputs

### ISSUE THREAD

**Issue by mcjudd** [edwindj/daff#9]
First of all, thank you for this fantastic package. I've used it successfully for several tasks, and have only recently come upon this issue.

**Issue:**

I get a cryptic message that pops up when I call `diff_data()` on two large datasets (one has 41,222 observations and 23 variables, and the other has 32,077 observations and 21 variables). Note that if I use `dplyr::slice` to chop each dataset to 10,000 rows each, the same error occurs.

**Attempted traceback:**

I was able to use `debugonce(diff_data)` to step through the function and believe I have identified the source. It appears to come during the call `ctx$assign(tv_diff$var_name, JS(diff))` (which of course I'm aware comes from the `V8` package, so please let me know if I ought to cross-post this issue in that repo's tracker as well or instead).

I step into `ctx$assign(tv_diff$var_name, JS(diff))`, which looks like this...

```
function (name, value, auto_unbox = TRUE, ...) 
{
  stopifnot(is.character(name))
  obj <- if (inherits(value, "JS_EVAL")) {
    invisible(this$eval(paste("var", name, "=", value)))
  }
  else {
    invisible(this$eval(paste("var", name, "=", toJSON(value, 
      auto_unbox = auto_unbox, ...))))
  }
}
```

... and then have no problems until I step into `invisible(this$eval(paste("var", name, "=", value)))`. It looks like the error ultimately occurs in `paste("var", name, "=", value)`, which calls `.Internal(paste(list(...), sep, collapse))`.

With all of the functions that I stepped through, I'm not sure if an issue with one or more functions in the `daff` package and/or the `V8` package caused the base system to hit a fault or if it's a problem with my own data (which is sensitive and unable to be shared). Apologies for the exceedingly circuitous traceback and lack of a reproducible example.

**Comment by paulfitz** [comment]
Chiming in since I recognize that error message. `Ordering took too long` is a debug statement from the underlying javascript version of daff https://github.com/edwindj/daff/blob/master/inst/js/daff.js#L253.  It was removed last year from https://github.com/paulfitz/daff and the code it came from was rewritten with something a bit more thought out.

**Comment by mcjudd** [comment]
Sorry to nag, just giving this issue a gentle "bump".

**Comment by jeroenooms** [comment]
I don't know anything about daff, but I tried to update the `js`the the latest version. If this works I'll send the PR. Can you try if this solves your problem:

```r
devtools::install_github("jeroenooms/daff")
```

**Comment by edwindj** [comment]
Merged the PR of @jeroenooms (Thx!).

**Comment by mcjudd** [comment]
A quick run on two related datasets containing one year of data was successful! I will check the rest of the years in my current analysis and then close the issue if the problem does not crop up again. Thanks @paulfitz, @jeroenooms, and @edwindj!

**Comment by edwindj** [comment]
On CRAN now :-)
